import smtplib
import ssl
from email.message import EmailMessage

def sendemail():
    # Variables for the sender and receivers information along with the subject, body, and taking input from the user to
    # insert their password.
    subject = "Yahoo Email From Python Script"
    body = input("Please enter the body of your email ")
    sender_email = input("Who is the Yahoo sender? ")
    receiver_email = input("Who is the receiver? ")
    # A one time password has been generated by yahoo. this goes into the password field
    password = input("Enter the senders one time password ")

    # using the email message library to create the message and assign it to the correct variables.
    message = EmailMessage()
    message['From'] = sender_email
    message['To'] = receiver_email
    message["Subject"] = subject
    message.set_content(body)

    # allows for a secure session to be created between the host and the server to send the email.
    #This uses the SSL encryption on port 465. This communicates & sends the email.
    context = ssl.create_default_context()
    print("sending email")
    with smtplib.SMTP_SSL("smtp.mail.yahoo.com", 465, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message.as_string())



def main():
    sendemail()
    print("success")


if __name__ == '__main__':
    main()
# See PyCharm help at https://www.jetbrains.com/help/pycharm/

